[project]
name = "frequensolve"
dynamic = [ "version", "classifiers" ]
description = "Python API for FrequenSolve finite element modeling tool"
authors = [{ name = "Jacob Badger", email = "jcbadger@utexas.edu" }]
keywords = ["seismic", "waveform", "geophysics", "modeling"]
readme = "README.md"
requires-python = ">=3.9,<3.14"
dependencies = [
    "matplotlib>=3.7,<4.0",
    "numpy>=1.24,<3.0",
    "pyfftw>=0.14,<0.15",
    "jinja2>=3.1.5,<4.0",
    "h5py>=3.12.1,<4.0",
    "pylops>=2.4.0,<3.0",
    "scipy>=1.13,<2.0",
    "pint>=0.24.4,<1.0",
    "gitpython>=3.1.44,<4.0"
]

[tool.poetry]
packages = [{ include = "frequensolve", from = "src" }]
version = "0.1.0"
classifiers = ["Development Status :: 4 - Beta"]

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
